-- ═══════════════════════════════════════════════════════════
-- FILMOTHÈQUE — Import des données (étape 3)
-- Copier-coller dans SQL Editor → Run
-- ═══════════════════════════════════════════════════════════

-- ── GENRES ──
INSERT INTO genres (id, name) VALUES ('g1', 'Drame');
INSERT INTO genres (id, name) VALUES ('g2', 'Crime');
INSERT INTO genres (id, name) VALUES ('g3', 'Romance');
INSERT INTO genres (id, name) VALUES ('g4', 'Comédie');
INSERT INTO genres (id, name) VALUES ('g5', 'Action');
INSERT INTO genres (id, name) VALUES ('g6', 'Science-Fiction');
INSERT INTO genres (id, name) VALUES ('g7', 'Aventure');
INSERT INTO genres (id, name) VALUES ('g8', 'Thriller');
INSERT INTO genres (id, name) VALUES ('g9', 'Mystère');
INSERT INTO genres (id, name) VALUES ('g10', 'Western');
INSERT INTO genres (id, name) VALUES ('g11', 'Guerre');
INSERT INTO genres (id, name) VALUES ('g12', 'Fantastique');
INSERT INTO genres (id, name) VALUES ('g13', 'Horreur');
INSERT INTO genres (id, name) VALUES ('g14', 'Familial');
INSERT INTO genres (id, name) VALUES ('g15', 'Histoire');

-- ── RÉALISATEURS ──
INSERT INTO directors (id, name) VALUES ('d1', 'Steven Spielberg');
INSERT INTO directors (id, name) VALUES ('d2', 'James Cameron');
INSERT INTO directors (id, name) VALUES ('d3', 'Martin Scorsese');
INSERT INTO directors (id, name) VALUES ('d4', 'Christopher Nolan');
INSERT INTO directors (id, name) VALUES ('d5', 'Baz Luhrmann');
INSERT INTO directors (id, name) VALUES ('d6', 'Quentin Tarantino');
INSERT INTO directors (id, name) VALUES ('d7', 'Danny Boyle');
INSERT INTO directors (id, name) VALUES ('d8', 'David Fincher');
INSERT INTO directors (id, name) VALUES ('d9', 'Martin Brest');
INSERT INTO directors (id, name) VALUES ('d10', 'Ridley Scott');
INSERT INTO directors (id, name) VALUES ('d11', 'Jonathan Demme');
INSERT INTO directors (id, name) VALUES ('d12', 'Bryan Singer');
INSERT INTO directors (id, name) VALUES ('d13', 'Steven Soderbergh');
INSERT INTO directors (id, name) VALUES ('d14', 'Brian De Palma');
INSERT INTO directors (id, name) VALUES ('d15', 'Cameron Crowe');
INSERT INTO directors (id, name) VALUES ('d16', 'Paul Thomas Anderson');
INSERT INTO directors (id, name) VALUES ('d17', 'Rob Reiner');
INSERT INTO directors (id, name) VALUES ('d18', 'Sydney Pollack');
INSERT INTO directors (id, name) VALUES ('d19', 'Bobby Farrelly');
INSERT INTO directors (id, name) VALUES ('d20', 'Shawn Levy');
INSERT INTO directors (id, name) VALUES ('d21', 'Jay Roach');
INSERT INTO directors (id, name) VALUES ('d22', 'John Landis');
INSERT INTO directors (id, name) VALUES ('d23', 'Robert Zemeckis');
INSERT INTO directors (id, name) VALUES ('d24', 'Chris Columbus');
INSERT INTO directors (id, name) VALUES ('d25', 'Nora Ephron');
INSERT INTO directors (id, name) VALUES ('d26', 'Frank Darabont');
INSERT INTO directors (id, name) VALUES ('d27', 'Ron Howard');
INSERT INTO directors (id, name) VALUES ('d28', 'Anthony Minghella');
INSERT INTO directors (id, name) VALUES ('d29', 'Clint Eastwood');
INSERT INTO directors (id, name) VALUES ('d30', 'Doug Liman');
INSERT INTO directors (id, name) VALUES ('d31', 'Peter Weir');
INSERT INTO directors (id, name) VALUES ('d32', 'Luc Besson');
INSERT INTO directors (id, name) VALUES ('d33', 'Massy Tadjedin');
INSERT INTO directors (id, name) VALUES ('d34', 'John Hughes');
INSERT INTO directors (id, name) VALUES ('d35', 'Jean-Jacques Annaud');

-- ── ACTEURS ──
INSERT INTO actors (id, name) VALUES ('a1', 'Leonardo DiCaprio');
INSERT INTO actors (id, name) VALUES ('a2', 'Tom Hanks');
INSERT INTO actors (id, name) VALUES ('a3', 'Christopher Walken');
INSERT INTO actors (id, name) VALUES ('a4', 'Kate Winslet');
INSERT INTO actors (id, name) VALUES ('a5', 'Billy Zane');
INSERT INTO actors (id, name) VALUES ('a6', 'Jonah Hill');
INSERT INTO actors (id, name) VALUES ('a7', 'Margot Robbie');
INSERT INTO actors (id, name) VALUES ('a8', 'Joseph Gordon-Levitt');
INSERT INTO actors (id, name) VALUES ('a9', 'Ken Watanabe');
INSERT INTO actors (id, name) VALUES ('a10', 'Tobey Maguire');
INSERT INTO actors (id, name) VALUES ('a11', 'Carey Mulligan');
INSERT INTO actors (id, name) VALUES ('a12', 'Mark Ruffalo');
INSERT INTO actors (id, name) VALUES ('a13', 'Ben Kingsley');
INSERT INTO actors (id, name) VALUES ('a14', 'Jamie Foxx');
INSERT INTO actors (id, name) VALUES ('a15', 'Christoph Waltz');
INSERT INTO actors (id, name) VALUES ('a16', 'Virginie Ledoyen');
INSERT INTO actors (id, name) VALUES ('a17', 'Guillaume Canet');
INSERT INTO actors (id, name) VALUES ('a18', 'John Travolta');
INSERT INTO actors (id, name) VALUES ('a19', 'Samuel L. Jackson');
INSERT INTO actors (id, name) VALUES ('a20', 'Uma Thurman');
INSERT INTO actors (id, name) VALUES ('a21', 'Harvey Keitel');
INSERT INTO actors (id, name) VALUES ('a22', 'Tim Roth');
INSERT INTO actors (id, name) VALUES ('a23', 'Michael Madsen');
INSERT INTO actors (id, name) VALUES ('a24', 'Lucy Liu');
INSERT INTO actors (id, name) VALUES ('a25', 'Vivica A. Fox');
INSERT INTO actors (id, name) VALUES ('a26', 'David Carradine');
INSERT INTO actors (id, name) VALUES ('a27', 'Daryl Hannah');
INSERT INTO actors (id, name) VALUES ('a28', 'Brad Pitt');
INSERT INTO actors (id, name) VALUES ('a29', 'Mélanie Laurent');
INSERT INTO actors (id, name) VALUES ('a30', 'Edward Norton');
INSERT INTO actors (id, name) VALUES ('a31', 'Helena Bonham Carter');
INSERT INTO actors (id, name) VALUES ('a32', 'Anthony Hopkins');
INSERT INTO actors (id, name) VALUES ('a33', 'Claire Forlani');
INSERT INTO actors (id, name) VALUES ('a34', 'Morgan Freeman');
INSERT INTO actors (id, name) VALUES ('a35', 'Gwyneth Paltrow');
INSERT INTO actors (id, name) VALUES ('a36', 'Michael Douglas');
INSERT INTO actors (id, name) VALUES ('a37', 'Sean Penn');
INSERT INTO actors (id, name) VALUES ('a38', 'Deborah Kara Unger');
INSERT INTO actors (id, name) VALUES ('a39', 'Tom Skerritt');
INSERT INTO actors (id, name) VALUES ('a40', 'Sigourney Weaver');
INSERT INTO actors (id, name) VALUES ('a41', 'Veronica Cartwright');
INSERT INTO actors (id, name) VALUES ('a42', 'Russell Crowe');
INSERT INTO actors (id, name) VALUES ('a43', 'Joaquin Phoenix');
INSERT INTO actors (id, name) VALUES ('a44', 'Connie Nielsen');
INSERT INTO actors (id, name) VALUES ('a45', 'Matt Damon');
INSERT INTO actors (id, name) VALUES ('a46', 'Jessica Chastain');
INSERT INTO actors (id, name) VALUES ('a47', 'Kristen Wiig');
INSERT INTO actors (id, name) VALUES ('a48', 'Jodie Foster');
INSERT INTO actors (id, name) VALUES ('a49', 'Scott Glenn');
INSERT INTO actors (id, name) VALUES ('a50', 'Kristen Stewart');
INSERT INTO actors (id, name) VALUES ('a51', 'Forest Whitaker');
INSERT INTO actors (id, name) VALUES ('a52', 'Stephen Baldwin');
INSERT INTO actors (id, name) VALUES ('a53', 'Gabriel Byrne');
INSERT INTO actors (id, name) VALUES ('a54', 'Benicio del Toro');
INSERT INTO actors (id, name) VALUES ('a55', 'George Clooney');
INSERT INTO actors (id, name) VALUES ('a56', 'Andy Garcia');
INSERT INTO actors (id, name) VALUES ('a57', 'Julia Roberts');
INSERT INTO actors (id, name) VALUES ('a58', 'Al Pacino');
INSERT INTO actors (id, name) VALUES ('a59', 'Tom Cruise');
INSERT INTO actors (id, name) VALUES ('a60', 'Jon Voight');
INSERT INTO actors (id, name) VALUES ('a61', 'Emmanuelle Béart');
INSERT INTO actors (id, name) VALUES ('a62', 'Dakota Fanning');
INSERT INTO actors (id, name) VALUES ('a63', 'Justin Chatwin');
INSERT INTO actors (id, name) VALUES ('a64', 'Samantha Morton');
INSERT INTO actors (id, name) VALUES ('a65', 'Colin Farrell');
INSERT INTO actors (id, name) VALUES ('a66', 'Penélope Cruz');
INSERT INTO actors (id, name) VALUES ('a67', 'Cameron Diaz');
INSERT INTO actors (id, name) VALUES ('a68', 'Philip Baker Hall');
INSERT INTO actors (id, name) VALUES ('a69', 'Philip Seymour Hoffman');
INSERT INTO actors (id, name) VALUES ('a70', 'Jack Nicholson');
INSERT INTO actors (id, name) VALUES ('a71', 'Demi Moore');
INSERT INTO actors (id, name) VALUES ('a72', 'Jeanne Tripplehorn');
INSERT INTO actors (id, name) VALUES ('a73', 'Gene Hackman');
INSERT INTO actors (id, name) VALUES ('a74', 'Matt Dillon');
INSERT INTO actors (id, name) VALUES ('a75', 'Ben Stiller');
INSERT INTO actors (id, name) VALUES ('a76', 'Carla Gugino');
INSERT INTO actors (id, name) VALUES ('a77', 'Dick Van Dyke');
INSERT INTO actors (id, name) VALUES ('a78', 'Robert De Niro');
INSERT INTO actors (id, name) VALUES ('a79', 'Teri Polo');
INSERT INTO actors (id, name) VALUES ('a80', 'Dustin Hoffman');
INSERT INTO actors (id, name) VALUES ('a81', 'Eddie Murphy');
INSERT INTO actors (id, name) VALUES ('a82', 'Judge Reinhold');
INSERT INTO actors (id, name) VALUES ('a83', 'John Ashton');
INSERT INTO actors (id, name) VALUES ('a84', 'Arsenio Hall');
INSERT INTO actors (id, name) VALUES ('a85', 'Shari Headley');
INSERT INTO actors (id, name) VALUES ('a86', 'Dan Aykroyd');
INSERT INTO actors (id, name) VALUES ('a87', 'Ralph Bellamy');
INSERT INTO actors (id, name) VALUES ('a88', 'Michael J. Fox');
INSERT INTO actors (id, name) VALUES ('a89', 'Christopher Lloyd');
INSERT INTO actors (id, name) VALUES ('a90', 'Crispin Glover');
INSERT INTO actors (id, name) VALUES ('a91', 'Macaulay Culkin');
INSERT INTO actors (id, name) VALUES ('a92', 'Joe Pesci');
INSERT INTO actors (id, name) VALUES ('a93', 'Daniel Stern');
INSERT INTO actors (id, name) VALUES ('a94', 'Billy Crystal');
INSERT INTO actors (id, name) VALUES ('a95', 'Meg Ryan');
INSERT INTO actors (id, name) VALUES ('a96', 'Carrie Fisher');
INSERT INTO actors (id, name) VALUES ('a97', 'Ross Malinger');
INSERT INTO actors (id, name) VALUES ('a98', 'Greg Kinnear');
INSERT INTO actors (id, name) VALUES ('a99', 'Catherine Zeta-Jones');
INSERT INTO actors (id, name) VALUES ('a100', 'Stanley Tucci');
INSERT INTO actors (id, name) VALUES ('a101', 'Helen Hunt');
INSERT INTO actors (id, name) VALUES ('a102', 'Chris Noth');
INSERT INTO actors (id, name) VALUES ('a103', 'David Morse');
INSERT INTO actors (id, name) VALUES ('a104', 'Bonnie Hunt');
INSERT INTO actors (id, name) VALUES ('a105', 'Robin Wright');
INSERT INTO actors (id, name) VALUES ('a106', 'Gary Sinise');
INSERT INTO actors (id, name) VALUES ('a107', 'Denzel Washington');
INSERT INTO actors (id, name) VALUES ('a108', 'Jason Robards');
INSERT INTO actors (id, name) VALUES ('a109', 'Tom Sizemore');
INSERT INTO actors (id, name) VALUES ('a110', 'Edward Burns');
INSERT INTO actors (id, name) VALUES ('a111', 'Bill Paxton');
INSERT INTO actors (id, name) VALUES ('a112', 'Kevin Bacon');
INSERT INTO actors (id, name) VALUES ('a113', 'Jude Law');
INSERT INTO actors (id, name) VALUES ('a114', 'Tony Kgoroge');
INSERT INTO actors (id, name) VALUES ('a115', 'Franka Potente');
INSERT INTO actors (id, name) VALUES ('a116', 'Chris Cooper');
INSERT INTO actors (id, name) VALUES ('a117', 'Clint Eastwood');
INSERT INTO actors (id, name) VALUES ('a118', 'Hilary Swank');
INSERT INTO actors (id, name) VALUES ('a119', 'Meryl Streep');
INSERT INTO actors (id, name) VALUES ('a120', 'Annie Corley');
INSERT INTO actors (id, name) VALUES ('a121', 'Christopher Carley');
INSERT INTO actors (id, name) VALUES ('a122', 'Bee Vang');
INSERT INTO actors (id, name) VALUES ('a123', 'Bradley Cooper');
INSERT INTO actors (id, name) VALUES ('a124', 'Sienna Miller');
INSERT INTO actors (id, name) VALUES ('a125', 'Kyle Gallner');
INSERT INTO actors (id, name) VALUES ('a126', 'Tim Robbins');
INSERT INTO actors (id, name) VALUES ('a127', 'Bob Gunton');
INSERT INTO actors (id, name) VALUES ('a128', 'Harrison Ford');
INSERT INTO actors (id, name) VALUES ('a129', 'Karen Allen');
INSERT INTO actors (id, name) VALUES ('a130', 'Paul Freeman');
INSERT INTO actors (id, name) VALUES ('a131', 'Robin Williams');
INSERT INTO actors (id, name) VALUES ('a132', 'Robert Sean Leonard');
INSERT INTO actors (id, name) VALUES ('a133', 'Ethan Hawke');
INSERT INTO actors (id, name) VALUES ('a134', 'Jean Reno');
INSERT INTO actors (id, name) VALUES ('a135', 'Natalie Portman');
INSERT INTO actors (id, name) VALUES ('a136', 'Gary Oldman');
INSERT INTO actors (id, name) VALUES ('a137', 'Anne Parillaud');
INSERT INTO actors (id, name) VALUES ('a138', 'Jean-Hugues Anglade');
INSERT INTO actors (id, name) VALUES ('a139', 'Tchéky Karyo');
INSERT INTO actors (id, name) VALUES ('a140', 'Jean-Marc Barr');
INSERT INTO actors (id, name) VALUES ('a141', 'Rosanna Arquette');
INSERT INTO actors (id, name) VALUES ('a142', 'Keira Knightley');
INSERT INTO actors (id, name) VALUES ('a143', 'Sam Worthington');
INSERT INTO actors (id, name) VALUES ('a144', 'Eva Mendes');
INSERT INTO actors (id, name) VALUES ('a145', 'Matthew Broderick');
INSERT INTO actors (id, name) VALUES ('a146', 'Alan Ruck');
INSERT INTO actors (id, name) VALUES ('a147', 'Mia Sara');
INSERT INTO actors (id, name) VALUES ('a148', 'Sean Connery');
INSERT INTO actors (id, name) VALUES ('a149', 'Christian Slater');
INSERT INTO actors (id, name) VALUES ('a150', 'Helmut Qualtinger');

-- ── FILMS ──
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('640', 'Arrête-moi si tu peux', 'Arrête-moi si tu peux', '2002', 'Dans les années soixante, le jeune Frank Abagnale Jr. est passé maître dans l’art de l’escroquerie, allant jusqu’à détourner 2,5 millions de dollars et à figurer sur les listes du FBI comme l’un des dix individus les plus recherchés des États‐Unis. Véritable caméléon, Frank revêt des identités aussi diverses que celles de pilote de ligne, de médecin, de professeur d’université ou encore d’assistant du procureur. Carl Hanratty, agent du FBI à l’apparence stricte, fait de la traque de Frank Abagnale Jr. sa mission prioritaire, mais ce dernier reste pendant longtemps insaisissable…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('597', 'Titanic', 'Titanic', '1997', 'Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le « Titanic », appareille pour son premier voyage. Quatre jours plus tard, il heurte un iceberg. À son bord, un artiste pauvre et une grande bourgeoise tombent amoureux.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('106646', 'Le Loup de Wall Street', 'Le Loup de Wall Street', '2013', 'Sa licence de courtier en poche, et les narines déjà pleines de cocaïne, Jordan Belfort est prêt à conquérir Wall Street. Ce jour d''octobre, un krach, le plus important depuis 1929, vient piétiner ses rêves de grandeur. C''est finalement à Long Island qu''il échoue et qu''il monte sa propre affaire de courtage. Son créneau : le hors-cote. Sa méthode : l''arnaque. Son équipe : des vendeurs ou des petits trafiquants.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('27205', 'Inception', 'Inception', '2010', 'Dom Cobb est un voleur expérimenté, le meilleur dans l''art dangereux de l''extraction, voler les secrets les plus intimes enfouis au plus profond du subconscient durant une phase de rêve, lorsque l''esprit est le plus vulnérable. Les capacités de Cobb ont fait des envieux dans le monde tourmenté de l''espionnage industriel alors qu''il devient fugitif en perdant tout ce qu''il a un jour aimé. Une chance de se racheter lui est alors offerte. Une ultime mission grâce à laquelle il pourrait retrouver sa vie passée mais uniquement s''il parvient à accomplir l''impossible inception.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('64682', 'Gatsby le Magnifique', 'Gatsby le Magnifique', '2013', 'Printemps 1922. L''époque est propice au relâchement des mœurs, à l''essor du jazz et à l’enrichissement des contrebandiers d’alcool… Apprenti écrivain, Nick Carraway quitte la région du Middle‐West pour s''installer à New York. Voulant sa part du rêve américain, il vit désormais entouré d''un mystérieux millionnaire, Jay Gatsby, qui s''étourdit en fêtes mondaines, et de sa cousine Daisy et de son mari volage, Tom Buchanan, issu de sang noble. C’est ainsi que Nick se retrouve au cœur du monde fascinant des milliardaires, de leurs illusions, de leurs amours et de leurs mensonges. Témoin privilégié de son temps, il se met à écrire une histoire où se mêlent des amours impossibles, des rêves d’absolu et des tragédies ravageuses et, chemin faisant, nous tend un miroir où se reflètent notre époque moderne et ses combats.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('11324', 'Shutter Island', 'Shutter Island', '2010', 'En 1954, le marshal Teddy Daniels et son coéquipier Chuck Aule sont envoyés enquêter sur l’île de Shutter Island, dans un hôpital psychiatrique où sont internés de dangereux criminels. L’une des patientes, Rachel Solando, a inexplicablement disparu. Comment la meurtrière a‐t‐elle pu sortir d’une cellule fermée de l’extérieur ? Le seul indice retrouvé dans la pièce est une feuille de papier sur laquelle on peut lire une suite de chiffres et de lettres sans signification apparente. Œuvre cohérente d’une malade, ou cryptogramme ?', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('68718', 'Django Unchained', 'Django Unchained', '2012', 'Dans le sud des États‐Unis, deux ans avant la guerre de Sécession, le Dr King Schultz, un chasseur de primes allemand, fait l’acquisition de Django, un esclave qui peut l’aider à traquer les frères Brittle, les meurtriers qu’il recherche. Schultz promet à Django de lui rendre sa liberté lorsqu’il aura capturé les Brittle – morts ou vifs. Alors que les deux hommes pistent les dangereux criminels, Django n’oublie pas que son seul but est de retrouver Broomhilda, sa femme, dont il fut séparé à cause du commerce des esclaves… Lorsque Django et Schultz arrivent dans l’immense plantation du puissant Calvin Candie, ils éveillent les soupçons de Stephen, un esclave qui sert Candie et a toute sa confiance. Le moindre de leurs mouvements est désormais épié par une dangereuse organisation de plus en plus proche… Si Django et Schultz veulent espérer s’enfuir avec Broomhilda, ils vont devoir choisir entre l’indépendance et la solidarité, entre le sacrifice et la survie…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('1907', 'La Plage', 'La Plage', '2000', 'Richard, jeune Américain, amateur de sensations inédites a choisi l''Asie comme terrain d''élection, dans l''espoir d''y vivre des aventures fortes et exaltantes. Dans un hôtel miteux de Bangkok boudé par les touristes, il fait la connaissance d''un couple de Francais, Françoise et Etienne. Dans la nuit, un homme au regard halluciné fait irruption dans sa chambre et évoque une île secrète, une plage paradisiaque, où il aurait vécu plusieurs années au sein d''une petite communauté d''esprits libres. Le lendemain, Richard retrouve une carte de l''île et le cadavre de Daffy.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('680', 'Pulp Fiction', 'Pulp Fiction', '1994', 'L’odyssée sanglante et burlesque de petits malfrats dans la jungle d’Hollywood : Deux petits tueurs, un dangereux gangster marié à une camée, un boxeur roublard, des prêteurs sur gages sadiques, un caïd élégant et dévoué, un dealer bon mari et deux tourtereaux à la gâchette facile.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('500', 'Reservoir Dogs', 'Reservoir Dogs', '1992', 'Après un hold‐up manqué, des cambrioleurs de haut vol font leurs comptes dans une confrontation violente, pour découvrir lequel d’entre eux les a trahis.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('24', 'Kill Bill : Volume 1', 'Kill Bill : Volume 1', '2003', 'Au cours d''un mariage, un commando armé massacre l''assistance, laissant pour morte la Mariée et l''enfant qu''elle porte. Après 4 ans de coma, la Mariée se lance à la poursuite des assassins, membres du clan de Bill, au sein duquel, sous le pseudonyme de Black Mamba, elle exerça elle-même autrefois ses talents de redoutable tueuse…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('393', 'Kill Bill : Volume 2', 'Kill Bill : Volume 2', '2004', 'Après avoir éliminé ses deux anciennes collègues Vernita Green et O-Ren Ishii, la Mariée, alias Black Mamba, poursuit l''éradication du gang des Vipères Assassines. Prochaines cibles : Budd, puis Elle Driver, avant d''atteindre enfin son but ultime : tuer leur chef, Bill…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('16869', 'Inglourious Basterds', 'Inglourious Basterds', '2009', 'Dans la France occupée de 1940, un groupe de soldats juifs américains, les bâtards, mène des actions punitives particulièrement sanglantes contre les nazis du Troisième Reich. Leur chemin rencontre celui de Shosanna Dreyfus, une jeune juive réfugiée à Paris exploitante d''une salle de cinéma qui entend elle aussi assouvir sa propre vengeance envers les nazis.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('550', 'Fight Club', 'Fight Club', '1999', 'Le narrateur, sans identité précise, vit seul, travaille seul, dort seul, mange seul ses plateaux‐repas pour une personne comme beaucoup d’autres personnes seules qui connaissent la misère humaine, morale et sexuelle. C’est pourquoi il va devenir membre du Fight club, un lieu clandestin où il va pouvoir retrouver sa virilité, l’échange et la communication. Ce club est dirigé par Tyler Durden, une sorte d’anarchiste entre gourou et philosophe qui prêche l’amour de son prochain.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('297', 'Rencontre avec Joe Black', 'Rencontre avec Joe Black', '1998', 'Une nuit, le magnat William Parrish ressent une violente douleur tandis qu''une voix surgissant des ténèbres lui annonce sa mort prochaine. À ce moment-là, un jeune inconnu se présente à son domicile pour l''accompagner vers son dernier voyage. Ce messager de l''au-delà impose à Parrish de l''héberger chez lui afin de lui donner l''occasion de partager un temps les expériences, les joies, les émotions et les drames des vivants, qui semblent lui être étrangers. En l''espace de trois jours, Joe Black révèlera toute la famille Parrish à elle-même.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('807', 'Seven', 'Seven', '1995', 'À New York, un criminel anonyme a décidé de commettre 7 meurtres basés sur les 7 pêchés capitaux énoncés dans la Bible : gourmandise, avarice, paresse, orgueil, luxure, envie et colère. Vieux flic blasé à 7 jours de la retraite, l''inspecteur Somerset mène l''enquête tout en formant son remplaçant, l''ambitieux inspecteur David Mills…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('2649', 'The Game', 'The Game', '1997', 'Nicholas Van Orton, homme d''affaires avisé, reçoit le jour de son anniversaire un étrange cadeau que lui offre son frère Conrad. Il s''agit d''un jeu. Nicholas découvre peu à peu que les enjeux en sont très élevés, bien qu''il ne soit certain ni des règles, ni même de l''objectif réel. Il prend peu à peu conscience qu''il est manipulé jusque dans sa propre maison par des conspirateurs inconnus qui semblent vouloir faire voler sa vie en éclats.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('348', 'Alien, le huitième passager', 'Alien', '1979', 'En 2122, le Nostromo, vaisseau de commerce, fait route vers la Terre avec à son bord un équipage de sept personnes en hibernation et une cargaison de minerais. Il interrompt soudain sa course suite à la réception d’un mystérieux message provenant d’une planète inexplorée. Réveillé par l’ordinateur de bord, l’équipage se rend sur place et découvre les restes d’un gigantesque vaisseau extraterrestre dont le seul passager semble être mort dans d’étranges circonstances…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('98', 'Gladiator', 'Gladiator', '2000', 'Le général romain Maximus est le plus fidèle soutien de l''empereur Marc Aurèle, qu''il a conduit de victoire en victoire avec une bravoure et un dévouement exemplaires. Jaloux du prestige de Maximus, et plus encore de l''amour que lui voue l''empereur, le fils de Marc Aurèle, Commode, s''arroge brutalement le pouvoir, puis ordonne l''arrestation du général et son exécution. Maximus échappe à ses assassins mais ne peut empêcher le massacre de sa famille. Capturé par un marchand d''esclaves, il devient gladiateur et prépare sa vengeance.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('286217', 'Seul sur Mars', 'Seul sur Mars', '2015', 'Au cours d’une mission spatiale habitée sur Mars, et à la suite d’un violent orage, l’astronaute Mark Watney est laissé pour mort et abandonné sur place par son équipage. Mais Watney a survécu et se retrouve seul sur cette planète hostile. Avec de maigres provisions, il ne doit compter que sur son ingéniosité, son bon sens et son intelligence pour survivre et trouver un moyen d’alerter la Terre qu’il est encore vivant. À des millions de kilomètres de là, la NASA et une équipe de scientifiques internationaux travaillent sans relâche pour ramener « le Martien » sur terre, pendant que, en parallèle, ses coéquipiers tentent secrètement d’organiser une audacieuse voire impossible mission de sauvetage.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('274', 'Le Silence des agneaux', 'Le Silence des agneaux', '1991', 'Un psychopathe connu sous le nom de Buffalo Bill sème la terreur dans le Middle West en kidnappant et en assassinant de jeunes femmes. Clarice Starling, une jeune stagiaire du FBI, est chargée d’interroger l’ex‐psychiatre Hannibal Lecter. Psychopathe redoutablement intelligent et porté sur le cannibalisme, Lecter est capable de lui fournir des informations concernant Buffalo Bill ainsi que son portrait psychologique. Mais il n’accepte de l’aider qu’en échange d’informations sur la vie privée de la jeune femme. Entre eux s’établit un lien de fascination et de répulsion.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('4547', 'Panic Room', 'Panic Room', '2002', 'Récemment séparée de son mari, Meg Altman est angoissée à l''idée de devoir élever seule sa fille Sarah. Elle achète une immense et splendide maison dans un quartier huppé à l''Ouest de New York. Son ancien propriétaire, un milliardaire, y a fait construire une pièce de sûreté dans laquelle on peut se réfugier en cas de menace extérieure et rester enfermé de nombreux jours grâce aux provisions qu''elle contient. Un soir, trois cambrioleurs pénètrent dans la maison avec la ferme intention de dérober une somme de 14 millions de dollars cachée par l''ancien maître des lieux. Ce butin serait-il dissimulé dans la pièce de sûreté, là où se sont réfugiées Meg et Sarah ?', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('629', 'Usual Suspects', 'Usual Suspects', '1995', 'Suspect numéro 1 dans une étrange affaire de hold-up, Verbal Kint est soumis à un interrogatoire par des agents fédéraux. Très vite, il dévoile aux policiers que le véritable cerveau de cette affaire n''est autre que le redoutable criminel Keyser Soze, un être machiavélique possédant une intelligence hors du commun. Peu à peu, le suspect va dresser un portrait effrayant de ce criminel que personne n''a jamais vu…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('161', 'Ocean''s Eleven', 'Ocean''s Eleven', '2001', 'À peine sorti de prison, Danny Ocean n''a qu''une idée en tête : organiser le casse du siècle en cambriolant les trois plus grands casinos de Las Vegas. Pour cela il réunit une équipe de malfrats spécialistes dans des domaines aussi variés que les explosifs, l''informatique, le bluff...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('163', 'Ocean''s Twelve', 'Ocean''s Twelve', '2004', 'Trois ans ont passé depuis le braquage historique du casino Bellagio de Las Vegas. Depuis, Danny Ocean et ses associés se sont dispersés dans la nature avec l''intention de mener une existence honnête. Remarié à Tess, ce dernier joue profil bas jusqu''au jour où Terry Benedict retrouve sa trace. Le propriétaire du Bellagio n''y va pas par quatre chemins: la bande doit, sous peine de mort, lui restituer le magot. Et ce n''est qu''un début, car quelqu''un d''autre s''intéresse de très près aux agissements de la bande des Onze...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('298', 'Ocean''s 13', 'Ocean''s Thirteen', '2007', 'Willy Bank n''aurait pas dû s''attaquer à un ami de Danny Ocean... Pour avoir trahi Reuben Tishkoff, Willy Bank, propriétaire sans scrupule d''un casino flambant neuf, va être sévèrement attaqué par toute l''équipe de Danny Ocean. Celle-ci n''aura plus qu''un objectif: infliger à Bank un châtiment exemplaire le soir de l''inauguration de son nouveau casino. Mais cette fois la chance ne leur suffira pas pour faire sauter The Bank...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('954', 'Mission : Impossible', 'Mission : Impossible', '1996', 'Ethan Hunt, un agent secret de haut niveau, est accusé de la mort de son équipe d''espionnage. Alors qu''il fuit les criminels du gouvernement, qu''il s''introduit dans la chambre forte la plus impénétrable de la CIA et qu''il se cramponne au toit d''un train à grande vitesse, Hunt se retrouve dans une course effrénée pour devancer ceux qui le poursuivent… et se rapprocher petit à petit d''une vérité bouleversante.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('74', 'La Guerre des mondes', 'La Guerre des mondes', '2005', 'Ray Ferrier est un docker divorcé et un père rien moins que parfait, qui n’entretient plus que des relations épisodiques avec son fils Robbie, 17 ans, et sa fille Rachel, 11 ans. Quelques minutes après que son ex‐femme et l’époux de cette dernière lui ont confié la garde des enfants, un puissant orage éclate. Ray assiste alors à un spectacle qui bouleversera à jamais sa vie…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('180', 'Minority Report', 'Minority Report', '2002', 'Washington, 2054. Plus aucun meurtre ne se produit grâce au « pré-crime », l’unité policière dirigée par John Anderton. Cette unité dispose d''un système lui permettant de visualiser les meurtres avant qu''ils ne se produisent. Mais quand John découvre qu''il est lui-même accusé d''un meurtre à venir, il n''a que 36 heures pour comprendre le véritable fonctionnement de ce système.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('1903', 'Vanilla Sky', 'Vanilla Sky', '2001', 'David Aames est un jeune et brillant éditeur new-yorkais qui a tout pour lui : l''argent, la réussite professionnelle et les femmes. Son ami Pelayo commet l''erreur de lui présenter Sofia, sa nouvelle compagne. Au premier regard, David succombe au charme de celle-ci. Tous les deux filent bientôt le parfait amour. Alors que David se dispute en voiture avec Julie, une ex folle de jalousie, la jeune femme accélère et c''est l''accident. Julie décède. Atrocement défiguré, David est transporté d''urgence à l''hôpital où les médecins ne peuvent réaliser de miracle. Sa vie bascule. Les gens ont dorénavant peur de lui et Sofia l''évite. Mais un matin, David se fait gentiment réveiller par celle-ci, qui lui déclare son amour. Les médecins lui annoncent même qu''il pourra retrouver son ancien visage. Réalité ou hallucination ?', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('334', 'Magnolia', 'Magnolia', '1999', 'Earl Partridge, âgé et malade, va bientôt mourir. Il demande à son fidèle infirmier de retrouver le fils qu''il a jadis abandonné. Sa jeune épouse, qui convoitait sa fortune, devrait se réjouir mais n''y parvient pas. Frank Mackey, jeune gourou cathodique de la séduction masculine, s''est construit un passé et une vie. Mais combien de temps le masque peut-il résister ? Toutes ces vies s''entrecroisent le temps d''une journée comme les autres sous le soleil de la Californie.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('881', 'Des hommes d''honneur', 'Des hommes d''honneur', '1992', 'Deux jeunes marines, Louden et Dawson, abattent, au cours d''une action disciplinaire désignée "Code Rouge", un de leur leurs camarades, Santiago. C''est le lieutenant Daniel Kaffee qui est désigné pour assurer leur défense lors de leur procès. Mais si Kaffee entame une défense de pure routine, sa jeune et pugnace adjointe, le lieutenant JoAnne Galoway, se rebiffe et l''oblige a instruire le dossier. Kaffee va devoir, pour découvrir la vérité sur cette affaire qui s''avère inquiétante, remonter jusqu''au sommet de la hiérarchie.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('37233', 'La Firme', 'La Firme', '1993', 'À la fin de ses études de droit, Mitch McDeere, brillant élément, est sollicité par plusieurs grands cabinets d''avocats. Il fixe son choix sur Bendini, Lambert & Locke, qui lui offrent les conditions les plus avantageuses. En contrepartie, il devra, comme chaque membre du cabinet, fournir quelque quatre-vingts heures de travail hebdomadaire. Il ignore encore qu''il vient de vendre son âme au diable.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('544', 'Mary à tout prix', 'Mary à tout prix', '1998', 'Ted, le loser, décide de retrouver son amour de jeunesse, la splendide Mary. Il engage un détective privé, Pat Healy, pour la retrouver. Persuadé qu''il a affaire à un dégénéré, Healy file à Miami et retrouve Mary. Elle est belle, gentille, s''occupe d''enfants handicapés et elle est célibataire. Decidé à garder Mary pour lui, il raconte à Ted qu''elle est devenue grosse, qu''elle est paralytique et qu''elle a quatre enfants. Mais Tucker, un architecte, est également amoureux de Mary. Il va faire cause commune avec Healy pour se débarrasser de Ted qui finalement a décidé de venir à Miami.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('1593', 'La Nuit au musée', 'La Nuit au musée', '2006', 'Le Muséum d''Histoire Naturelle renferme dans ses murs un secret mystérieux et stupéfiant que Larry, nouveau gardien de sécurité, ne va pas tarder à découvrir avec affolement : la nuit, toutes les expositions prennent vie ! Sous ses yeux, les soldats romains et les cow-boys miniatures se lancent dans une guerre acharnée, Attila et ses Huns commencent à piller les expositions avoisinantes, la momie tente de sortir de son sarcophage, le squelette du redoutable – mais néanmoins attachant – tyrannosaure rôde dans les couloirs... Le chaos est total ! Larry pourra-t-il remettre de l''ordre dans ses collections et sauver le musée ?', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('1597', 'Mon beau-père et moi', 'Mon beau-père et moi', '2000', 'Greg Focker, un modeste infirmier de Chicago, vit depuis deux mois avec la charmante Pam Byrnes et rêve d''officialiser leur union. Ravie de sa proposition, la jeune femme insiste pour un strict respect des règles bourgeoises : Greg devra obtenir l''accord de son père, Jack.Deux semaines plus tard, le couple fait son apparition dans la luxueuse résidence des Byrnes. Accueilli à bras ouverts par la mère de Pam, Dina, Greg décèle d''emblée une certaine froideur chez Jack. Ce dernier ne compte pas "céder" sa fille chérie au premier venu.Bien décidé à emporter la mise, Greg, nerveux, se met en quatre pour s''attirer la sympathie et le respect de son beau-père, ancien agent de la CIA, mais toutes ses amabilités, toutes ses plaisanteries tombent à plat face à cet homme crispé, possessif et paranoïaque.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('693', 'Mon beau-père, mes parents et moi', 'Mon beau-père, mes parents et moi', '2004', 'Greg Focker est un brave infirmier qui accumule les déboires, les maladresses et les faux-pas. Soucieux de plaire à tout le monde et de faire oublier son nom grotesque, sa première entrevue avec ses futurs beaux-parents Jack et Dina Byrnes fut un concentré exemplaire de tout ce qu''il ne faut pas faire dans de telles circonstances. Entre-temps, les choses se sont arrangées, et Greg a même réussi à amadouer le terrifiant Jack et à intégrer son cercle de confiance. Pam et lui peuvent donc envisager le mariage, mais il reste à organiser une réunion entre les Byrnes et les Focker. Un paisible week-end en Floride dans la propriété de Bernie et Roz Focker - lui fervent libéral, elle sexologue militante - permettra enfin aux deux familles de lier connaissance. Un ultime examen de passage, qui ne devrait pas poser de problème…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('90', 'Le Flic de Beverly Hills', 'Le Flic de Beverly Hills', '1984', 'Axel Foley, ancien voyou, est maintenant un des flics les plus efficaces de Detroit. Et même si ses méthodes sont loin d''être traditionnelles, ses supérieurs sont bien obligés de reconnaître ses qualités. Axel retrouve un ami d’enfance, mais celui-ci est assassiné le jour de leurs retrouvailles. L''enquête lui étant refusée, Axel prend ses congés et se lance à la poursuite du meurtrier. Le petit flic de Detroit se retrouve à Beverly Hills, entraîné dans le milieu des dealers et des truands…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('9602', 'Un prince à New York', 'Un prince à New York', '1988', 'Au royaume africain du Zamunda, son altesse royale, le prince Akeem célèbre ses 21 ans, devant ainsi majeur et doit se marier. Depuis son plus jeune âge, des servantes toutes dévouées ont toujours satisfait le moindre de ses désirs, même les plus intimes et parfait à son éducations royale. Ses parents, le roi Jaffe Joffer et la reine Aoleon, lui ont choisi une future épouse, Imani Izzi, qui n''a été élevée que pour servir le futur roi. Toutefois, le futur roi ne veut pas d''une femme dévouée à sa vie, il souhaite rencontrer une femme en accord avec ses sentiments, avec une personnalité. Pour se faire, et en dissimulant une partie de la vérité à ses royaux parents, Akeem gagne New York, dans le quartier du Queens avec son serviteur Semmi où il entreprend de vivre dans une pauvreté factice pour trouver la femme idéale.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('1621', 'Un fauteuil pour deux', 'Un fauteuil pour deux', '1983', 'D''un côté, Louis Winthorpe III, un jeune directeur, est chargé des investissements chez Duke & Duke, une puissante banque de Philadelphie. De l''autre, Billy Ray Valentine est un noir combinard mais fauché. Tous deux vont faire l''objet d''un pari insensé, passé entre les patrons de Louis.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('105', 'Retour vers le futur', 'Retour vers le futur', '1985', 'En 1985, Marty, un adolescent comme les autres, mène une existence morne et ennuyeuse. Heureusement, il est épris de la jolie Jennifer et entretient une profonde amitié avec Doc, un savant fou qui prétend avoir inventé une machine à explorer le temps. Un jour, Doc invite Marty à l''essayer…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('771', 'Maman, j''ai raté l''avion !', 'Maman, j''ai raté l''avion', '1990', 'La famille McCallister a décidé de passer les fêtes de Noël à Paris. Seulement Kate et Peter McCallister s''aperçoivent dans l''avion qu''il leur manque le plus jeune de leurs enfants, Kevin, âgé de 9 ans. D''abord désespéré, Kevin reprend vite les choses en main et s''organise pour vivre le mieux possible. Quand deux cambrioleurs choisissent sa maison pour commettre leurs méfaits.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('772', 'Maman, j''ai encore raté l''avion !', 'Maman, j''ai encore raté l''avion', '1992', 'Après Paris, c''est à Miami que la tribu McCallister décide de passer les fêtes de Noël. À l''aube du jour J, toute la famille est sur le pied de guerre et file a l''aéroport en prenant bien garde de ne pas oublier Kevin. Mais celui-ci s''éclipse pour acheter des piles pour son walkman, il ne retrouve plus les siens et s''embarque par mégarde pour New York...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('639', 'Quand Harry rencontre Sally…', 'Quand Harry rencontre Sally', '1989', 'Lorsqu''ils se rencontrent pour la première fois dans les années 70, Harry et Sally ne s''apprécient pas, mais alors pas du tout. Ils se quittent, jurant de ne plus se revoir. Cinq ans plus tard, ils se retrouvent mais rien n''a changé : leurs avis sur les relations hommes-femmes divergent du tout au tout. Cinq autres années passent, et Harry rencontre Sally à nouveau. Ils se racontent leurs expériences, leurs déceptions et se rendent compte que leur vie amoureuse est un désastre. Mais l''amitié entre Harry et Sally est-elle possible ?', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('858', 'Nuits Blanches à Seattle', 'Nuits blanches à Seattle', '1993', 'Annie Reed, journaliste, s''émeut quand elle entend à la radio l''histoire de Sam Baldwin. Touchée par cette histoire, elle tente d''entrer en contact avec Sam, malgré l''approche de son mariage avec Walter et la distance qui sépare Seattle de Baltimore. C''est le début d''une course à l''amour.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('9489', 'Vous avez un mess@ge', 'Vous avez un message', '1998', 'Tous les deux sont libraires. Kathleen tient une échoppe au charme suranné, The Shop Around the Corner, et a initié aux joies de la lecture des ribambelles d''enfants tandis que Joe possède une chaîne de librairies de grande surface, Fox Books, qui a rapidement éliminé ses concurrentes. Kathleen hait plus que tout au monde Fox Books tandis que Joe attend nonchalamment de rayer des librairies celle de Kathlen. Ils ne se connaissent pas mais se croisent tous les jours et surtout comme dans le film de Lubitsch échangent une correspondance follement amoureuse par le biais d''Internet.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('594', 'Le Terminal', 'Le Terminal', '2004', 'Viktor Navorski est l’un de ces milliers de touristes, venus des quatre coins du monde, qui débarquent chaque jour à l’Aéroport JFK de New York. Mais, à quelques heures de son arrivée, voilà qu’un coup d’État bouleverse sa petite république d’Europe Centrale, mettant celle‐ci au ban des nations et faisant de Viktor… un apatride. Les portes de l’Amérique se ferment devant lui, alors même que se bouclent les frontières de son pays: Viktor est bel et bien coincé…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('8358', 'Seul au monde', 'Seul au monde', '2000', 'Chuck Noland, gestionnaire au service d’un transporteur international, ne vit que par son travail. Il sillonne le monde pour améliorer les performances de son entreprise et la productivité de ses équipes. Il ne voit sa compagne Kelly que quelques jours par an. Lors de l’un de ses déplacements, Chuck est victime d’un accident d''avion qui coule en plein Pacifique. Agrippé à un radeau de sauvetage, Chuck s’échoue sur un îlot désert. Seul au monde, privé de tous ses repères habituels, le naufragé doit apprendre les gestes élémentaires pour sa survie.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('497', 'La Ligne verte', 'La Ligne verte', '1999', 'Paul Edgecomb, pensionnaire centenaire d’une maison de retraite, est hanté par ses souvenirs. Gardien-chef du pénitencier de Cold Mountain en 1935, il était chargé de veiller au bon déroulement des exécutions des peines capitales, en s’efforçant d’adoucir les derniers moments des condamnés. Parmi eux, se trouvait un colosse du nom de John Coffey, accusé du viol et du meurtre de deux fillettes. Intrigué par cet homme candide et timide, aux dons magiques, Edgecomb va tisser avec lui des liens très forts.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('13', 'Forrest Gump', 'Forrest Gump', '1994', 'À Savannah, État de Géorgie, Forrest Gump, assis sur un banc public, livre à qui veut l’entendre, l’étrange récit de sa vie mouvementée sur trois décennies. Il naît dans un bourg de l’Alabama, affecté d’un quotient intellectuel inférieur à la moyenne et d’une paralysie partielle des jambes. Souvent raillé à l’école, le jeune Forrest se lie d’amitié avec Jenny. Propulsé de l''état d''handicapé physique à celui de vedette du football, de héros du Vietnam au roi de la crevette, des honneurs de la Maison Blanche au bonheur d''une histoire d''amour, Forrest est le symbole d''une époque, un candide dans une Amérique qui a perdu son innocence.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('9800', 'Philadelphia', 'Philadelphia', '1993', 'Andrew Beckett, brillant avocat, est appelé à une carriere fulgurante. Adulé par son milieu, rien ne semble pouvoir ralentir son ascension. Mais, le jour où ses associés apprennent qu''Andrew est atteint du sida, ils n''hésitent pas à pretexter une faute professionnelle pour justifier son renvoi. Andrew décide de ne pas se laisser faire et attaque le cabinet pour licenciement abusif.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('857', 'Il faut sauver le soldat Ryan', 'Il faut sauver le soldat Ryan', '1998', 'Vue à travers le regard d’une escouade de soldats américains, l’histoire débute le jour du Débarquement au cours de la 2ème Guerre Mondiale, le long des plages de Normandie. Le capitaine John Miller a pour mission de retrouver le soldat James Ryan, dont les trois frères sont morts au combat et il s’expose ainsi à de nombreux risques. Confrontés à une situation périlleuse, les hommes discutent les ordres. Pourquoi huit hommes risqueraient-ils leur vie pour un seul homme ? Rattrapés par la brutalité de la guerre, chacun cherche sa propre réponse ainsi que la force de vaincre un futur incertain avec honneur, décence et courage.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('568', 'Apollo 13', 'Apollo 13', '1995', 'Après les premiers pas de l''homme sur la Lune, la NASA décide de poursuivre les vols habités. Jim Lovell qui, deux ans plus tôt, avait participé au vol Apollo 8, est choisi pour diriger la mission Apollo 13. Avec Fred Haise et Ken Mattingly, il suit un entraînement intensif. Une semaine avant le départ prévu, les médecins détectent chez Ken Mattingly des signes de rougeole. À contrecœur, Jim Lovell doit se résigner à le remplacer par Jack Swigert, insuffisamment préparé à son goût. Le jour du lancement, le 11 avril 1970, Apollo 13 décolle de Cap Kennedy, dans l''indifférence générale. Jusqu''au troisième jour, tout se passe bien…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('1213', 'Le Talentueux M. Ripley', 'Le Talentueux Mr Ripley', '1999', 'Tom Ripley, jeune homme désargenté mais ambitieux, attire l’attention d’un riche vieillard, Herbert Greenleaf, qui le charge de convaincre son fils Dickie, exilé en Italie, de rentrer aux États‐Unis. Sur place, Tom se laisse fasciner par l’existence insouciante et dorée que mène le jeune oisif. Il adopte ses goûts, imite son comportement, désire sa compagne, et va jusqu’à s’éprendre de Dickie lui‐même. Celui‐ci, dans un premier temps, traite Tom comme un ami mais, très vite, il commence à le trouver encombrant, pour ne pas dire énervant. Un jour, alors qu’ils sont seuls en mer, Tom avoue son amour à Dickie, qui le repousse violemment. Le conflit qui s’ensuit se termine par la mort de Dickie…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('22954', 'Invictus', 'Invictus', '2009', 'En 1994, l''élection de Nelson Mandela consacre la fin de l''Apartheid, mais l''Afrique du Sud reste une nation profondément divisée sur le plan racial et économique. Pour unifier le pays et donner à chaque citoyen un motif de fierté, Mandela mise sur le sport, et fait cause commune avec le capitaine de la modeste équipe de rugby sud-africaine. Leur pari: se présenter à la coupe du monde de rugby de 1995...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('2501', 'La Mémoire dans la peau', 'La Mémoire dans la peau', '2002', 'Un homme entre la vie et la mort est tiré de l’océan par un bateau de pêche italien. Ayant retrouvé ses esprits, il se rend compte qu’il souffre d’amnésie totale et qu’il n’a sur lui aucun papier d’identité. Les nombreux talents qu’il se découvre, techniques de combat et connaissances de plusieurs langues, lui suggèrent un passé dangereux. Aidé de la d’abord récalcitrante Marie, il s’engage dans une recherche désespérée pour retrouver son identité et la raison qui pousse d’impitoyables assassins à le traquer.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('70', 'Million Dollar Baby', 'Million Dollar Baby', '2004', 'Rejeté depuis longtemps par sa fille, l’entraîneur Frankie Dunn s’est replié sur lui‐même et vit dans un désert affectif, en évitant toute relation qui pourrait accroître sa douleur et sa culpabilité. Le jour où Maggie Fitzgerald, 31 ans, pousse la porte de son gymnase à la recherche d’un coach, elle n’amène pas seulement avec elle sa jeunesse et sa force, mais aussi une histoire jalonnée d’épreuves et une exigence, vitale et urgente : monter sur le ring, entraînée par Frankie, et enfin concrétiser le rêve d’une vie. Après avoir repoussé plusieurs fois sa demande, Frankie se laisse convaincre par l’inflexible détermination de la jeune femme. Une relation mouvementée, tour à tour stimulante et exaspérante, se noue entre eux, au fil de laquelle Maggie et l’entraîneur se découvrent une communauté d’esprit et une complicité inattendues…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('688', 'Sur la route de Madison', 'Sur la route de Madison', '1995', 'À la mort de leur mère, Michael Johnson et sa sœur Caroline se retrouvent dans la ferme où ils ont passé leur enfance, dans l''Iowa. Ils apprennent avec consternation que la défunte, Francesca, a demandé que ses cendres soient répandues du haut du pont de Roseman. Une bizarrerie que la lecture du journal intime de Francesca va expliquer. Jadis, au cours de l''été 1965, alors que son mari et ses deux enfants s''absentent pour quelques jours, Francesca voit arriver une camionnette bringuebalante. Robert Kincaid, un photographe sexagénaire, en descend et lui demande le chemin du pont de Roseman. Plutôt que de le lui expliquer, Francesca décide de lui montrer le chemin...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('13223', 'Gran Torino', 'Gran Torino', '2008', 'Walt Kowalski est un ancien de la guerre de Corée, un homme inflexible, amer et pétri de préjugés surannés. Après des années de travail à la chaîne, il vit replié sur lui-même, occupant ses journées à bricoler, traînasser et siroter des bières. Avant de mourir, sa femme exprima le vœu qu''il aille à confesse, mais Walt n''a rien à avouer, ni personne à qui parler. Hormis sa chienne Daisy, il ne fait confiance qu''à son M-1, toujours propre, toujours prêt à l''usage… Ses anciens voisins ont déménagé ou sont morts depuis longtemps. Son quartier est aujourd''hui peuplé d''immigrants asiatiques qu''il méprise, et Walt ressasse ses haines, innombrables - à l''encontre de ses voisins, des ados Hmong, latinos et afro-américains « qui croient faire la loi », de ses propres enfants, devenus pour lui des étrangers. Walt tue le temps comme il peut, en attendant le grand départ, jusqu''au jour où un ado Hmong du quartier tente de lui voler sa précieuse Ford Gran Torino…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('190859', 'American Sniper', 'American Sniper', '2014', 'Tireur d’élite des Navy SEAL, Chris Kyle est envoyé en Irak dans un seul but : protéger ses camarades. Sa précision chirurgicale sauve d’innombrables vies humaines sur le champ de bataille et, tandis que les récits de ses exploits se multiplient, il décroche le surnom de « La Légende ». Cependant, sa réputation se propage au-delà des lignes ennemies, si bien que sa tête est mise à prix et qu’il devient une cible privilégiée des insurgés. Malgré le danger, et l’angoisse dans laquelle vit sa famille, Chris participe à quatre batailles décisives parmi les plus terribles de la guerre en Irak, s’imposant ainsi comme l’incarnation vivante de la devise des SEAL : « Pas de quartier ! ». Mais en rentrant au pays, Chris prend conscience qu’il ne parvient pas à retrouver une vie normale.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('278', 'Les Évadés', 'Les Évadés', '1994', 'En 1947, Andy Dufresne, un jeune banquier, est condamné à la prison à vie pour le meurtre de sa femme et de son amant. Ayant beau clamer son innocence, il est emprisonné à Shawshank, le pénitencier le plus sévère de l''État du Maine. Il y fait la rencontre de Red, un noir désabusé, détenu depuis vingt ans. Commence alors une grande histoire d''amitié entre les deux hommes…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('85', 'Les Aventuriers de l''arche perdue', 'Les Aventuriers de l''arche perdue', '1981', 'L''Arche d''Alliance contenant les tables de la Loi brisées par Moïse, voici 3.000 ans, est l''objet de la convoitise des nazis. L''archéologue aventurier Indiana Jones se lance à sa recherche, poursuivi par son ennemi Belloq.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('207', 'Le Cercle des poètes disparus', 'Le Cercle des poètes disparus', '1989', 'Todd Anderson est un garçon plutôt timide. Désormais élève de la prestigieuse académie Welton, réputée pour être l''une des plus fermées et austères des États-Unis, tout le monde attend de lui qu''il suive les traces de son frère, qui avait fait à Welton de brillantes études.  C''est là qu''il va faire la rencontre de M. Keating, un professeur de lettres anglaises qui, c''est le moins que l''on puisse dire, sort des sentiers battus. Jour après jour, M. Keating encourage ses élèves à penser par eux-mêmes et à refuser l''ordre établi. Cette rencontre va bouleverser la vie du jeune Todd, mais aussi celle de ses amis.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('101', 'Léon', 'Léon', '1994', 'Léon est un tueur professionnel redoutable et insaisissable. Il vit seul à New York avec sa plante verte et ses habitudes jusqu''au jour où une petite Mathilda de douze ans sonne à sa porte et fait irruption dans sa vie.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('9322', 'Nikita', 'Nikita', '1991', 'Le braquage d''une pharmacie par une bande de junkies en manque de drogue tourne mal : une fusillade cause la mort de plusieurs personnes dont un policier, abattu par la jeune Nikita. Condamnée à la prison à perpétuité, celle-ci fait bientôt la rencontre de Bob, un homme mystérieux qui contraint la jeune femme à travailler secrètement pour le gouvernement. Après quelques rébellions lors d''un entraînement intensif de plusieurs années, Nikita devient un agent hautement qualifié des services secrets, capable désormais selon Bob d''évoluer seule à l''extérieur. Celui-ci espère d''ailleurs s''en assurer lors d''une terrible mise à l''épreuve au cours de laquelle Nikita doit éliminer un pilier de la mafia asiatique au beau milieu d''un restaurant bondé...', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('175', 'Le Grand Bleu', 'Le Grand Bleu', '1988', 'C''est l''histoire de deux apnéistes, Jacques Mayol et Enzo Molinari. Leur aventure commence dans les îles grecques dès les années 50. Gamins, les deux plongeurs se disputent déjà tous les records des profondeurs. Vingt ans plus tard, ils se retrouvent concurrents au même championnat. «Le grand bleu», c''est l''amitié de ces deux hommes, liés définitivement à la mer.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('23830', 'Last Night', 'Last Night', '2011', 'Joanna et Michael vivent à New York. Aucun nuage, aucun doute n’est jamais venu assombrir leur union, jusqu’à ce que chacun d’eux soit tenté, la même nuit… Pendant que Michael est en déplacement professionnel avec Laura, jeune femme aussi attirante qu’énigmatique, Joanna recroise Alex, l’autre grand amour de sa vie. Les 36 heures qui suivent vont obliger chacun à faire des choix…', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('9377', 'La Folle Journée de Ferris Bueller', 'La Folle Journée de Ferris Bueller', '1986', 'Ferris Bueller, un adolescent populaire et charmeur mais aussi cancre invétéré, convainc sa petite amie et son meilleur ami hypocondriaque (dont le père a une Ferrari) de sécher les cours pour aller passer la journée à Chicago. Pendant qu’ils font les 400 coups dans la grande ville, le proviseur et la sœur de Ferris tentent, chacun de leurs côtés, de prouver aux parents que leur fils est un cancre et qu’il a séché.', FALSE);
INSERT INTO films (id, title, fr_title, year, overview, seen) VALUES ('192', 'Le Nom de la rose', 'Le Nom de la rose', '1986', 'En l’an 1327, dans une abbaye bénédictine, des moines disparaissent. Un franciscain, Guillaume de Baskerville, mène l’enquête, aidé du jeune novice Adso von Melk. C’est l’époque où l’Église, en pleine crise, se voit disputer son pouvoir spirituel et temporel. C’est aussi l’apogée de l’Inquisition.', FALSE);

-- ── AFFICHES ──
INSERT INTO posters (film_id, url) VALUES ('640', 'https://image.tmdb.org/t/p/w500/nafyoqVGi87AwaV51GSJ0pk97gs.jpg');
INSERT INTO posters (film_id, url) VALUES ('597', 'https://image.tmdb.org/t/p/w500/vpsvHLkoeKUjceIMeNSqCp3xEyY.jpg');
INSERT INTO posters (film_id, url) VALUES ('106646', 'https://image.tmdb.org/t/p/w500/dQIQZbJXn1pflQw3nwvXLJX0dHa.jpg');
INSERT INTO posters (film_id, url) VALUES ('27205', 'https://image.tmdb.org/t/p/w500/aej3LRUga5rhgkmRP6XMFw3ejbl.jpg');
INSERT INTO posters (film_id, url) VALUES ('64682', 'https://image.tmdb.org/t/p/w500/apvQQZTVLTEHrkQiDdUe3jUDY9Y.jpg');
INSERT INTO posters (film_id, url) VALUES ('11324', 'https://image.tmdb.org/t/p/w500/fQ0vGVTtxjCdAJnxwPZ88O3Wzrh.jpg');
INSERT INTO posters (film_id, url) VALUES ('68718', 'https://image.tmdb.org/t/p/w500/vRXUnWrXUgXRoX0BaEcuNMfyeQt.jpg');
INSERT INTO posters (film_id, url) VALUES ('1907', 'https://image.tmdb.org/t/p/w500/iH0mQA6Zn0RRZy3UvHhgwUAOq7V.jpg');
INSERT INTO posters (film_id, url) VALUES ('680', 'https://image.tmdb.org/t/p/w500/4TBdF7nFw2aKNM0gPOlDNq3v3se.jpg');
INSERT INTO posters (film_id, url) VALUES ('500', 'https://image.tmdb.org/t/p/w500/p61wwD0jWfgbhg9Ja9uoDZdS8YE.jpg');
INSERT INTO posters (film_id, url) VALUES ('24', 'https://image.tmdb.org/t/p/w500/udRaQKzT0LG4iQFxHLaYjno9uAT.jpg');
INSERT INTO posters (film_id, url) VALUES ('393', 'https://image.tmdb.org/t/p/w500/852ZvIARe3CISnX9t96unwSHyoL.jpg');
INSERT INTO posters (film_id, url) VALUES ('16869', 'https://image.tmdb.org/t/p/w500/lPKwFzX4TiWLA4Mo5Bnf8aIIrJm.jpg');
INSERT INTO posters (film_id, url) VALUES ('550', 'https://image.tmdb.org/t/p/w500/t1i10ptOivG4hV7erkX3tmKpiqm.jpg');
INSERT INTO posters (film_id, url) VALUES ('297', 'https://image.tmdb.org/t/p/w500/5I66ZaHmUbZ9HgK34fFVeQPeAWP.jpg');
INSERT INTO posters (film_id, url) VALUES ('807', 'https://image.tmdb.org/t/p/w500/upIOOLVeOoUkTM5fVWwXW2JmBrW.jpg');
INSERT INTO posters (film_id, url) VALUES ('2649', 'https://image.tmdb.org/t/p/w500/2sUcLRG3ZwE8JOrCzk3M6GyCsTx.jpg');
INSERT INTO posters (film_id, url) VALUES ('348', 'https://image.tmdb.org/t/p/w500/l8CES84JndFlNfBNMxdLRYaLvI6.jpg');
INSERT INTO posters (film_id, url) VALUES ('98', 'https://image.tmdb.org/t/p/w500/5gJOu3t2QrznuJqjCG7FQDMI76t.jpg');
INSERT INTO posters (film_id, url) VALUES ('286217', 'https://image.tmdb.org/t/p/w500/51CqiKVStZ2YPx64iPs3LDDiQnt.jpg');
INSERT INTO posters (film_id, url) VALUES ('274', 'https://image.tmdb.org/t/p/w500/sSQDxwm4r28YpJSQVyVOtpYVs0E.jpg');
INSERT INTO posters (film_id, url) VALUES ('4547', 'https://image.tmdb.org/t/p/w500/hZRbJ9a7YhdDOx8BECb8svI6qOQ.jpg');
INSERT INTO posters (film_id, url) VALUES ('629', 'https://image.tmdb.org/t/p/w500/h06jDZB4Y9YQJiSGTcUwbhuiUrB.jpg');
INSERT INTO posters (film_id, url) VALUES ('161', 'https://image.tmdb.org/t/p/w500/sLiFrrQn2iqfn3gYciJF1yqJCOU.jpg');
INSERT INTO posters (film_id, url) VALUES ('163', 'https://image.tmdb.org/t/p/w500/x2lepGLOFv6XijMVl0mFpIs16AG.jpg');
INSERT INTO posters (film_id, url) VALUES ('298', 'https://image.tmdb.org/t/p/w500/73OQ7Qlkq6bpNJytnvQLpQs4boa.jpg');
INSERT INTO posters (film_id, url) VALUES ('954', 'https://image.tmdb.org/t/p/w500/RzurOKfiw5DrKkcyjXMBjQ7xHq.jpg');
INSERT INTO posters (film_id, url) VALUES ('74', 'https://image.tmdb.org/t/p/w500/b2GIYpfFuO43ailnUFGER9LDa2Q.jpg');
INSERT INTO posters (film_id, url) VALUES ('180', 'https://image.tmdb.org/t/p/w500/91dfWOkpjlqPkbZDjAjrReFqXQP.jpg');
INSERT INTO posters (film_id, url) VALUES ('1903', 'https://image.tmdb.org/t/p/w500/rP5pOnQ7kZrPOOCGay2Vc1O84Z0.jpg');
INSERT INTO posters (film_id, url) VALUES ('334', 'https://image.tmdb.org/t/p/w500/klhJK5KvHbWkGkO1x5bXzOfQAWp.jpg');
INSERT INTO posters (film_id, url) VALUES ('881', 'https://image.tmdb.org/t/p/w500/vsjxwIGaA8GP79pgtv6dqRhRsPu.jpg');
INSERT INTO posters (film_id, url) VALUES ('37233', 'https://image.tmdb.org/t/p/w500/qVlqbEiuZ05ZwoGxjNckomuwbe8.jpg');
INSERT INTO posters (film_id, url) VALUES ('544', 'https://image.tmdb.org/t/p/w500/ad8kLFbtBqey2z1dYvcxyNVisMB.jpg');
INSERT INTO posters (film_id, url) VALUES ('1593', 'https://image.tmdb.org/t/p/w500/iF88HSUPHFDPqW6jp4o8h40lbHC.jpg');
INSERT INTO posters (film_id, url) VALUES ('1597', 'https://image.tmdb.org/t/p/w500/cEd840xfKawjUGjcnJj41KS3yBM.jpg');
INSERT INTO posters (film_id, url) VALUES ('693', 'https://image.tmdb.org/t/p/w500/cCdZBRQbdlHu6Yyfp8GEEDZhgWV.jpg');
INSERT INTO posters (film_id, url) VALUES ('90', 'https://image.tmdb.org/t/p/w500/wL8sSSJy4fYlIODtEmVgsx8qYOA.jpg');
INSERT INTO posters (film_id, url) VALUES ('9602', 'https://image.tmdb.org/t/p/w500/fesM5L7mwuuBIRSOA9l7xXSNHH.jpg');
INSERT INTO posters (film_id, url) VALUES ('1621', 'https://image.tmdb.org/t/p/w500/kU21ARWABQqoY2a5VRwDxVusT9G.jpg');
INSERT INTO posters (film_id, url) VALUES ('105', 'https://image.tmdb.org/t/p/w500/iCgFtDUZxN8iUzNBCisjUrBmg2q.jpg');
INSERT INTO posters (film_id, url) VALUES ('771', 'https://image.tmdb.org/t/p/w500/g0QlNeZzMkqyHfbSeoBCTcFNLWL.jpg');
INSERT INTO posters (film_id, url) VALUES ('772', 'https://image.tmdb.org/t/p/w500/gFhf8NwvEKCbNIOQZxLqj1i5DMy.jpg');
INSERT INTO posters (film_id, url) VALUES ('639', 'https://image.tmdb.org/t/p/w500/3LKgUlcBVobOmQ85cLwGycLP3LJ.jpg');
INSERT INTO posters (film_id, url) VALUES ('858', 'https://image.tmdb.org/t/p/w500/6N6F80zYR3tFhDt2zIAFtK4TH6.jpg');
INSERT INTO posters (film_id, url) VALUES ('9489', 'https://image.tmdb.org/t/p/w500/37KXAYL2A7wlQSiCHCRSZUoJL0K.jpg');
INSERT INTO posters (film_id, url) VALUES ('594', 'https://image.tmdb.org/t/p/w500/2ornUh2bi1PRsuTARDuOSJK8tO7.jpg');
INSERT INTO posters (film_id, url) VALUES ('8358', 'https://image.tmdb.org/t/p/w500/w1bnhSkcT4pa2KQZzRoq0BHBn8T.jpg');
INSERT INTO posters (film_id, url) VALUES ('497', 'https://image.tmdb.org/t/p/w500/cRBUYC02CPsVa1GqBq6rfHn5a8g.jpg');
INSERT INTO posters (film_id, url) VALUES ('13', 'https://image.tmdb.org/t/p/w500/zi6RNYK1vXjIvpSBgjatXRcFYh2.jpg');
INSERT INTO posters (film_id, url) VALUES ('9800', 'https://image.tmdb.org/t/p/w500/nOw0nfcTQ7L1YkvUUrjgNyu7KPK.jpg');
INSERT INTO posters (film_id, url) VALUES ('857', 'https://image.tmdb.org/t/p/w500/mlSsQWIQV0NKIqqRQRI0yi9gqk8.jpg');
INSERT INTO posters (film_id, url) VALUES ('568', 'https://image.tmdb.org/t/p/w500/sOi7PkJXcdEAck9p12s0A7SXqaX.jpg');
INSERT INTO posters (film_id, url) VALUES ('1213', 'https://image.tmdb.org/t/p/w500/vU4qTwtFpYF5EDsQwxqn4B83hzk.jpg');
INSERT INTO posters (film_id, url) VALUES ('22954', 'https://image.tmdb.org/t/p/w500/4zpsqUf8XFzk4sYbGSXBap1bQKh.jpg');
INSERT INTO posters (film_id, url) VALUES ('2501', 'https://image.tmdb.org/t/p/w500/osEb1avYb9MvGUCOIIX0fiXUXDN.jpg');
INSERT INTO posters (film_id, url) VALUES ('70', 'https://image.tmdb.org/t/p/w500/7yWwlgq12qZ4nMLQHhEf8ITaggn.jpg');
INSERT INTO posters (film_id, url) VALUES ('688', 'https://image.tmdb.org/t/p/w500/tSqlgE0vUG896MiK9YHBPe0buNO.jpg');
INSERT INTO posters (film_id, url) VALUES ('13223', 'https://image.tmdb.org/t/p/w500/sVmDIIFPzbyEz87dZYpLfetn4Lm.jpg');
INSERT INTO posters (film_id, url) VALUES ('190859', 'https://image.tmdb.org/t/p/w500/9BEN7zRpoLBaBU3t97kPJkHUgnv.jpg');
INSERT INTO posters (film_id, url) VALUES ('278', 'https://image.tmdb.org/t/p/w500/t30GjttOdb5At1sYy8b3TOwFgWV.jpg');
INSERT INTO posters (film_id, url) VALUES ('85', 'https://image.tmdb.org/t/p/w500/nTsllJhHBDZndFudSB2RgeHuQAt.jpg');
INSERT INTO posters (film_id, url) VALUES ('207', 'https://image.tmdb.org/t/p/w500/oHBdsvdlPhzkJZOfax7Oy3X5mm7.jpg');
INSERT INTO posters (film_id, url) VALUES ('101', 'https://image.tmdb.org/t/p/w500/efqJtlo5J1hBNFmbwyjyAR9Mpr2.jpg');
INSERT INTO posters (film_id, url) VALUES ('9322', 'https://image.tmdb.org/t/p/w500/jLqvVdR1gucaMF5wtCAOS9nsolY.jpg');
INSERT INTO posters (film_id, url) VALUES ('175', 'https://image.tmdb.org/t/p/w500/eoO9OkhstHjgODeUAlW2xr6BxRD.jpg');
INSERT INTO posters (film_id, url) VALUES ('23830', 'https://image.tmdb.org/t/p/w500/6orMRIVqbQPtuMT14j35rVaLski.jpg');
INSERT INTO posters (film_id, url) VALUES ('9377', 'https://image.tmdb.org/t/p/w500/uK8fRkPfQH3nLLOX5WVEA5E2HK.jpg');
INSERT INTO posters (film_id, url) VALUES ('192', 'https://image.tmdb.org/t/p/w500/bpi3PEGT4674CrUjj2rqOkUuoAp.jpg');

-- ── RELATIONS FILMS ↔ GENRES ──
INSERT INTO film_genres (film_id, genre_id) VALUES ('640', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('640', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('597', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('597', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('106646', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('106646', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('106646', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('27205', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('27205', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('27205', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('64682', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('64682', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('11324', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('11324', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('11324', 'g9');
INSERT INTO film_genres (film_id, genre_id) VALUES ('68718', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('68718', 'g10');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1907', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1907', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1907', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1907', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('680', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('680', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('680', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('500', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('500', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('24', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('24', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('393', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('393', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('393', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('16869', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('16869', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('16869', 'g11');
INSERT INTO film_genres (film_id, genre_id) VALUES ('550', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('550', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('297', 'g12');
INSERT INTO film_genres (film_id, genre_id) VALUES ('297', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('297', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('807', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('807', 'g9');
INSERT INTO film_genres (film_id, genre_id) VALUES ('807', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2649', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2649', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2649', 'g9');
INSERT INTO film_genres (film_id, genre_id) VALUES ('348', 'g13');
INSERT INTO film_genres (film_id, genre_id) VALUES ('348', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('98', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('98', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('98', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('286217', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('286217', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('286217', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('274', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('274', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('274', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('4547', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('4547', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('4547', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('629', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('629', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('629', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('161', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('161', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('163', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('163', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('298', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('298', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('954', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('954', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('954', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('74', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('74', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('74', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('180', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('180', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('180', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1903', 'g9');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1903', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1903', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('334', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('881', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('37233', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('37233', 'g9');
INSERT INTO film_genres (film_id, genre_id) VALUES ('37233', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('544', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('544', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1593', 'g12');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1593', 'g14');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1593', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1597', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1597', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('693', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('693', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('90', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('90', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('90', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9602', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9602', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1621', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('105', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('105', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('105', 'g6');
INSERT INTO film_genres (film_id, genre_id) VALUES ('771', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('771', 'g14');
INSERT INTO film_genres (film_id, genre_id) VALUES ('772', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('772', 'g14');
INSERT INTO film_genres (film_id, genre_id) VALUES ('772', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('639', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('639', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('639', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('858', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('858', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('858', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9489', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9489', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('594', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('594', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('8358', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('8358', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('497', 'g12');
INSERT INTO film_genres (film_id, genre_id) VALUES ('497', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('497', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('13', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('13', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('13', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9800', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('857', 'g11');
INSERT INTO film_genres (film_id, genre_id) VALUES ('857', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('857', 'g15');
INSERT INTO film_genres (film_id, genre_id) VALUES ('568', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('568', 'g15');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1213', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1213', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('1213', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('22954', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('22954', 'g15');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2501', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2501', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2501', 'g9');
INSERT INTO film_genres (film_id, genre_id) VALUES ('2501', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('70', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('688', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('688', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('13223', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('190859', 'g11');
INSERT INTO film_genres (film_id, genre_id) VALUES ('190859', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('278', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('278', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('85', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('85', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('207', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('101', 'g2');
INSERT INTO film_genres (film_id, genre_id) VALUES ('101', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('101', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9322', 'g5');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9322', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('175', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('175', 'g7');
INSERT INTO film_genres (film_id, genre_id) VALUES ('175', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('23830', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('23830', 'g3');
INSERT INTO film_genres (film_id, genre_id) VALUES ('9377', 'g4');
INSERT INTO film_genres (film_id, genre_id) VALUES ('192', 'g1');
INSERT INTO film_genres (film_id, genre_id) VALUES ('192', 'g8');
INSERT INTO film_genres (film_id, genre_id) VALUES ('192', 'g9');

-- ── RELATIONS FILMS ↔ ACTEURS ──
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('640', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('640', 'a2', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('640', 'a3', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('597', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('597', 'a4', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('597', 'a5', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('106646', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('106646', 'a6', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('106646', 'a7', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('27205', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('27205', 'a8', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('27205', 'a9', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('64682', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('64682', 'a10', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('64682', 'a11', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('11324', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('11324', 'a12', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('11324', 'a13', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('68718', 'a14', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('68718', 'a15', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('68718', 'a1', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1907', 'a1', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1907', 'a16', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1907', 'a17', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('680', 'a18', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('680', 'a19', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('680', 'a20', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('500', 'a21', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('500', 'a22', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('500', 'a23', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('24', 'a20', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('24', 'a24', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('24', 'a25', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('393', 'a20', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('393', 'a26', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('393', 'a27', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('16869', 'a28', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('16869', 'a29', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('16869', 'a15', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('550', 'a30', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('550', 'a28', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('550', 'a31', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('297', 'a28', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('297', 'a32', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('297', 'a33', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('807', 'a34', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('807', 'a28', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('807', 'a35', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('2649', 'a36', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('2649', 'a37', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('2649', 'a38', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('348', 'a39', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('348', 'a40', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('348', 'a41', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('98', 'a42', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('98', 'a43', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('98', 'a44', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('286217', 'a45', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('286217', 'a46', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('286217', 'a47', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('274', 'a48', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('274', 'a32', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('274', 'a49', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('4547', 'a48', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('4547', 'a50', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('4547', 'a51', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('629', 'a52', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('629', 'a53', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('629', 'a54', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('161', 'a55', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('161', 'a28', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('161', 'a56', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('163', 'a55', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('163', 'a57', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('163', 'a28', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('298', 'a55', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('298', 'a28', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('298', 'a58', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('954', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('954', 'a60', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('954', 'a61', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('74', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('74', 'a62', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('74', 'a63', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('180', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('180', 'a64', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('180', 'a65', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1903', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1903', 'a66', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1903', 'a67', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('334', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('334', 'a68', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('334', 'a69', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('881', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('881', 'a70', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('881', 'a71', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('37233', 'a59', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('37233', 'a72', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('37233', 'a73', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('544', 'a67', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('544', 'a74', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('544', 'a75', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1593', 'a75', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1593', 'a76', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1593', 'a77', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1597', 'a75', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1597', 'a78', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1597', 'a79', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('693', 'a75', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('693', 'a78', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('693', 'a80', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('90', 'a81', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('90', 'a82', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('90', 'a83', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9602', 'a81', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9602', 'a84', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9602', 'a85', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1621', 'a86', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1621', 'a81', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1621', 'a87', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('105', 'a88', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('105', 'a89', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('105', 'a90', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('771', 'a91', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('771', 'a92', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('771', 'a93', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('772', 'a91', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('772', 'a92', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('772', 'a93', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('639', 'a94', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('639', 'a95', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('639', 'a96', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('858', 'a95', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('858', 'a2', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('858', 'a97', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9489', 'a95', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9489', 'a2', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9489', 'a98', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('594', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('594', 'a99', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('594', 'a100', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('8358', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('8358', 'a101', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('8358', 'a102', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('497', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('497', 'a103', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('497', 'a104', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('13', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('13', 'a105', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('13', 'a106', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9800', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9800', 'a107', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9800', 'a108', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('857', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('857', 'a109', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('857', 'a110', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('568', 'a2', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('568', 'a111', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('568', 'a112', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1213', 'a45', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1213', 'a35', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('1213', 'a113', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('22954', 'a34', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('22954', 'a45', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('22954', 'a114', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('2501', 'a45', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('2501', 'a115', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('2501', 'a116', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('70', 'a117', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('70', 'a118', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('70', 'a34', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('688', 'a119', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('688', 'a117', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('688', 'a120', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('13223', 'a117', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('13223', 'a121', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('13223', 'a122', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('190859', 'a123', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('190859', 'a124', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('190859', 'a125', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('278', 'a126', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('278', 'a34', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('278', 'a127', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('85', 'a128', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('85', 'a129', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('85', 'a130', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('207', 'a131', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('207', 'a132', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('207', 'a133', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('101', 'a134', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('101', 'a135', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('101', 'a136', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9322', 'a137', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9322', 'a138', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9322', 'a139', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('175', 'a140', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('175', 'a134', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('175', 'a141', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('23830', 'a142', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('23830', 'a143', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('23830', 'a144', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9377', 'a145', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9377', 'a146', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('9377', 'a147', 2);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('192', 'a148', 0);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('192', 'a149', 1);
INSERT INTO film_actors (film_id, actor_id, cast_order) VALUES ('192', 'a150', 2);

-- ── RELATIONS FILMS ↔ RÉALISATEURS ──
INSERT INTO film_directors (film_id, director_id) VALUES ('640', 'd1');
INSERT INTO film_directors (film_id, director_id) VALUES ('597', 'd2');
INSERT INTO film_directors (film_id, director_id) VALUES ('106646', 'd3');
INSERT INTO film_directors (film_id, director_id) VALUES ('27205', 'd4');
INSERT INTO film_directors (film_id, director_id) VALUES ('64682', 'd5');
INSERT INTO film_directors (film_id, director_id) VALUES ('11324', 'd3');
INSERT INTO film_directors (film_id, director_id) VALUES ('68718', 'd6');
INSERT INTO film_directors (film_id, director_id) VALUES ('1907', 'd7');
INSERT INTO film_directors (film_id, director_id) VALUES ('680', 'd6');
INSERT INTO film_directors (film_id, director_id) VALUES ('500', 'd6');
INSERT INTO film_directors (film_id, director_id) VALUES ('24', 'd6');
INSERT INTO film_directors (film_id, director_id) VALUES ('393', 'd6');
INSERT INTO film_directors (film_id, director_id) VALUES ('16869', 'd6');
INSERT INTO film_directors (film_id, director_id) VALUES ('550', 'd8');
INSERT INTO film_directors (film_id, director_id) VALUES ('297', 'd9');
INSERT INTO film_directors (film_id, director_id) VALUES ('807', 'd8');
INSERT INTO film_directors (film_id, director_id) VALUES ('2649', 'd8');
INSERT INTO film_directors (film_id, director_id) VALUES ('348', 'd10');
INSERT INTO film_directors (film_id, director_id) VALUES ('98', 'd10');
INSERT INTO film_directors (film_id, director_id) VALUES ('286217', 'd10');
INSERT INTO film_directors (film_id, director_id) VALUES ('274', 'd11');
INSERT INTO film_directors (film_id, director_id) VALUES ('4547', 'd8');
INSERT INTO film_directors (film_id, director_id) VALUES ('629', 'd12');
INSERT INTO film_directors (film_id, director_id) VALUES ('161', 'd13');
INSERT INTO film_directors (film_id, director_id) VALUES ('163', 'd13');
INSERT INTO film_directors (film_id, director_id) VALUES ('298', 'd13');
INSERT INTO film_directors (film_id, director_id) VALUES ('954', 'd14');
INSERT INTO film_directors (film_id, director_id) VALUES ('74', 'd1');
INSERT INTO film_directors (film_id, director_id) VALUES ('180', 'd1');
INSERT INTO film_directors (film_id, director_id) VALUES ('1903', 'd15');
INSERT INTO film_directors (film_id, director_id) VALUES ('334', 'd16');
INSERT INTO film_directors (film_id, director_id) VALUES ('881', 'd17');
INSERT INTO film_directors (film_id, director_id) VALUES ('37233', 'd18');
INSERT INTO film_directors (film_id, director_id) VALUES ('544', 'd19');
INSERT INTO film_directors (film_id, director_id) VALUES ('1593', 'd20');
INSERT INTO film_directors (film_id, director_id) VALUES ('1597', 'd21');
INSERT INTO film_directors (film_id, director_id) VALUES ('693', 'd21');
INSERT INTO film_directors (film_id, director_id) VALUES ('90', 'd9');
INSERT INTO film_directors (film_id, director_id) VALUES ('9602', 'd22');
INSERT INTO film_directors (film_id, director_id) VALUES ('1621', 'd22');
INSERT INTO film_directors (film_id, director_id) VALUES ('105', 'd23');
INSERT INTO film_directors (film_id, director_id) VALUES ('771', 'd24');
INSERT INTO film_directors (film_id, director_id) VALUES ('772', 'd24');
INSERT INTO film_directors (film_id, director_id) VALUES ('639', 'd17');
INSERT INTO film_directors (film_id, director_id) VALUES ('858', 'd25');
INSERT INTO film_directors (film_id, director_id) VALUES ('9489', 'd25');
INSERT INTO film_directors (film_id, director_id) VALUES ('594', 'd1');
INSERT INTO film_directors (film_id, director_id) VALUES ('8358', 'd23');
INSERT INTO film_directors (film_id, director_id) VALUES ('497', 'd26');
INSERT INTO film_directors (film_id, director_id) VALUES ('13', 'd23');
INSERT INTO film_directors (film_id, director_id) VALUES ('9800', 'd11');
INSERT INTO film_directors (film_id, director_id) VALUES ('857', 'd1');
INSERT INTO film_directors (film_id, director_id) VALUES ('568', 'd27');
INSERT INTO film_directors (film_id, director_id) VALUES ('1213', 'd28');
INSERT INTO film_directors (film_id, director_id) VALUES ('22954', 'd29');
INSERT INTO film_directors (film_id, director_id) VALUES ('2501', 'd30');
INSERT INTO film_directors (film_id, director_id) VALUES ('70', 'd29');
INSERT INTO film_directors (film_id, director_id) VALUES ('688', 'd29');
INSERT INTO film_directors (film_id, director_id) VALUES ('13223', 'd29');
INSERT INTO film_directors (film_id, director_id) VALUES ('190859', 'd29');
INSERT INTO film_directors (film_id, director_id) VALUES ('278', 'd26');
INSERT INTO film_directors (film_id, director_id) VALUES ('85', 'd1');
INSERT INTO film_directors (film_id, director_id) VALUES ('207', 'd31');
INSERT INTO film_directors (film_id, director_id) VALUES ('101', 'd32');
INSERT INTO film_directors (film_id, director_id) VALUES ('9322', 'd32');
INSERT INTO film_directors (film_id, director_id) VALUES ('175', 'd32');
INSERT INTO film_directors (film_id, director_id) VALUES ('23830', 'd33');
INSERT INTO film_directors (film_id, director_id) VALUES ('9377', 'd34');
INSERT INTO film_directors (film_id, director_id) VALUES ('192', 'd35');